[build]
    publish = "_site/"
    command = "make && make test"
    functions = "functions/"

[[redirects]]
    from = "https://kektura-szakaszok.netlify.app/*"
    to = "https://kektura-szakaszok.lencse.io/:splat"
    force = true

[dev]
    publish = "_site/"
